### PR TITLE
Fix notification sticking around after clicking [X] 

### LINKED ISSUE #3859: /u/andytuba on [bug] New Comment popup takes multiple clicks to close
Clicking [x] button notification then mousing over notification cancels close</p>

https://www.reddit.com/r/RESissues/comments/5mpbfx/bug_new_comment_popup_takes_multiple_clicks_to/dc64qr1/

### PR DESCRIPTION
**Pull request by andytuba**
Fixes #3859

### CODE REVIEW

File: lib/modules/notifications.js [hunk 1]
```diff
@@ -312,19 +312,19 @@ function setCloseNotificationTimer({ currentTarget: thisNotification }: Event |
...
-function cancelCloseNotificationTimer(e: Event) {
-	const thisNotificationID = +e.currentTarget.getAttribute('id').split('-')[1];
-	e.currentTarget.classList.remove('timerOn');
-	e.currentTarget.removeAttribute('style');
+function cancelCloseNotificationTimer({ currentTarget: thisNotification }: Event) {
+	const thisNotificationID = +thisNotification.getAttribute('id').split('-')[1];
+	thisNotification.classList.remove('timerOn');
+	thisNotification.removeAttribute('style');
 	clearTimeout(notificationTimers[thisNotificationID]);
-	e.target.removeEventListener('mouseenter', cancelCloseNotificationTimer);
```
Comment (andytuba) [inline lib/modules/notifications.js]: This is the source of the bug -- should've been `e.currentTarget`.
