### PR TITLE
Fix command line settings search

### LINKED ISSUE #3860: RES Command line `settings some search query` doesn't search for query
at least it loads the search page

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #3860

### CODE REVIEW

File: tests/commandLine.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+module.exports = {
+	'basic functionality': browser => {
+		browser
+			.url('https://www.reddit.com/wiki/pages/')
+			.waitForElementVisible('#RESSettingsButton')
+			.keys([browser.keys['.']])
+			.assert.visible('#keyCommandLineWidget')
+			.keys([browser.keys.SHIFT, browser.keys.SLASH]) // "?"
+			.assert.containsText('#keyCommandForm', 'navigates to subreddit')
```
Comment (andytuba) [inline tests/commandLine.js]: That'll fail when it gets i18n'd.  How about some command name, or bullet points or something?

Comment (erikdesjardins) [inline tests/commandLine.js]:
```
erik [6:27 PM] I'll explicitly make it `en.reddit.com` so it's not i18n'd if that sounds good, since there's not much else to look for (classless <li>s, but they could be empty if it bugs out)
andytuba [6:29 PM] +1
```
