### PR TITLE
Prevent Hover from closing when mouse is inside selected item

### LINKED ISSUE #3494: Multireddit navigation popup disappears before you can hover over it
Repro steps:
- visit a multi
- hover over the currently selected multi
- move mouse towards popup

This could be a Firefox only issue, @andytuba mentioned on irc:

> <andytuba> but in chrome it works fine for me if i move my mouse directly from the tab onto the menu

Browser: Firefox 49.0.1 x64, RES: 5.0.2.

### PR DESCRIPTION
**Pull request by Express50**
Fixes #3494.

Due to the extra padding on the selected navbar item, the hover div overlaps the selected item div when it is visible. This causes the `mouseleave` event to be fired (as seen [here](https://jsfiddle.net/1LwqLdsm/1/)). To fix this, I added a check before calling Hover.close() from the `mouseleave` event, as well as remove other unnecessary calls to Hover.close().

Relevant issue: #3494
Tested in browser: chrome

### CODE REVIEW

File: lib/modules/hover.js [hunk 1]
```diff
@@ -161,7 +161,6 @@ class Hover {
 	}
 
 	target(element: JQuery | HTMLElement) {
-		this.close();
```
Comment (erikdesjardins) [inline lib/modules/hover.js]: Removing this prevents you from hovering on something else while it's fading out:
temp

(it's more noticeable when moving between multireddits)

**Comment by Express50** [comment]
@erikdesjardins can you please take another look at this? I think I fixed the issue with the hover not showing up again.

**Comment by erikdesjardins** [comment]
Sorry about the delay, 5.8.5 took longer than expected.

Everything seems good now, thanks!
