### PR TITLE
Fix goMode

### LINKED ISSUE #3136: goMode navigation menu shows no destinations
@larsjohnsen ideas?

### PR DESCRIPTION
**Pull request by larsjohnsen**
Closes #3136 

Updates the descriptions to match the behavior.

### CODE REVIEW

File: lib/modules/keyboardNav.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import _ from 'lodash';
 import linkAnnotationTemplate from '../templates/linkAnnotation.mustache';
 import { $ } from '../vendor';
 import * as Modules from '../core/modules';
+import goModePanelTemplate from '../templates/goModePanel.mustache';
```
Comment (erikdesjardins) [inline lib/modules/keyboardNav.js]: Nit: move this next to the other imported template

File: lib/modules/keyboardNav.js [hunk 2]
```diff
@@ -1153,85 +1169,63 @@ function navigateTo(newWindow, thisHREF) {
...
 
-module.goMode = function() {
-	if (!module.options.useGoMode.value) {
-		return;
-	}
+function toggleGoMode() {
 	goModeActive = !goModeActive;
 	if (goModeActive) {
 		$('body').on('keyup', handleGoModeEscapeKey);
 		$(document.body).append(goModePanel().fadeIn());
```
Comment (erikdesjardins) [inline lib/modules/keyboardNav.js]: We need to change this to something like `goModePanel().appendTo(document.body).fadeIn()` because jQuery 3 no longer treats disconnected elements as hidden
