### PR TITLE
imgur: allow exactly 5 or 7 char ids (not 6), and an [a-z] suffix

### LINKED ISSUE #2911: Imgur expando doesn't work sometimes
EX: https://www.reddit.com/r/DotA2/comments/4faum5/infographic_on_slightly_relevant_statistics_from/d27bwe4

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2911.

This has the added benefit of ignoring size suffixes on 5-char ids.

### CODE REVIEW

**Comment by andytuba** [comment]
:+1: This regex just gets gnarlier and gnarlier.

File: lib/modules/hosts/imgur.js [hunk 1]
```diff
@@ -31,8 +31,8 @@ addLibrary('mediaHosts', 'imgur', {
 	// was too greedy a search...
 	// the hashRe below was provided directly by MrGrim (well, everything after the domain was), using that now.
 	// in addition to the above, the album index was moved out of the first capture group.
-	hashRe: /^https?:\/\/(?:i\.|m\.|edge\.|www\.)*imgur\.com\/(?:r\/\w+\/)*(?!gallery)(?!removalrequest)(?!random)(?!memegen)(\w{5,7}(?:[&,]\w{5,7})*)(?:#\d+)?[sbtmlh]?(\.(?:jpe?g|gif|png|gifv))?(\?.*)?$/i,
-	hostedHashRe: /^https?:(\/\/i\.\w+\.*imgur\.com\/)(\w{5,7}(?:[&,]\w{5,7})*)(?:#\d+)?[sbtmlh]?(\.(?:jpe?g|gif|png))?(\?.*)?$/i,
+	hashRe: /^https?:\/\/(?:i\.|m\.|edge\.|www\.)*imgur\.com\/(?:r\/\w+\/)*(?!gallery)(?!removalrequest)(?!random)(?!memegen)(\w{5}(?:\w{2})?(?:[&,]\w{5}(?:\w{2})?)*)(?:#\d+)?[a-z]?(\.(?:jpe?g|gif|png|gifv))?(\?.*)?$/i,
```
Comment (andytuba) [inline lib/modules/hosts/imgur.js]: Now that we've already merged it, what about `(\w{5}|\w{7})` instead of +2?
