### PR TITLE
quickMessage: open from the "send message" link on user pages

### LINKED ISSUE #2167: QM does not work on /u/userpage "send message" link

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2167

### CODE REVIEW

File: lib/modules/quickMessage.js [hunk 1]
```diff
@@ -152,33 +152,26 @@ addModule('quickMessage', function(module, moduleID) {
...
-					module.openQuickMessageDialog({'to': '/r/' + subreddit});
-				}
-			});
-		}
+		function messageLinkEventHandler(event) {
+			if (event.which === 1) {
+				event.preventDefault();
 
-		if (module.options.openInlineLinks.value) {
-			$('div.content').on('click', 'a[href*="/message/compose"]', function(e) {
```
Comment (andytuba) [inline lib/modules/quickMessage.js]: It's probably worth sanity checking that the link either exactly starts with `/message/compose` or matches `^https?://blah.reddit.com/message/compose`

**Comment by andytuba** [comment]
Nifty! Nice and generic, should neatly handle any custom "message the mod" links added to sidebar.

File: lib/modules/quickMessage.js (hunk 1 above)
Comment (erikdesjardins) [inline lib/modules/quickMessage.js]: That should take care of it.
