### PR TITLE
Fix NER on the modlog and comments listings

### LINKED ISSUE #2617: NER on comments page is broken
https://www.reddit.com/r/RESissues/comments/40foq4/announcement_res_460_release_report_bugs_here/cyuzfn6?context=3

This might be as easy as fixing the includes for NER to include comments listings.

### LINKED ISSUE #2656: NER doesn't work on the modlog (/about/log)
https://www.reddit.com/r/RESissues/comments/41qxpr/bug_or_removed_feature_selecting_comments/

This is a bit more complicated than #2617 - it runs on the page but doesn't work.

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2656, fixes #2617

### CODE REVIEW

File: lib/modules/neverEndingReddit.js [hunk 1]
```diff
@@ -110,31 +113,26 @@ addModule('neverEndingReddit', {
...
 			this.allLinks = RESUtils.$things();
 
+			var nextLink = nextPrevLinks.next;
+			if (nextLink) {
+				this.nextPageURL = nextLink.getAttribute('href');
+				var nextXY = RESUtils.getXYpos(nextLink);
+				this.nextPageScrollY = nextXY.y;
 
-			// get the first link to the next page of reddit...
-			var nextPrevLinks = modules['neverEndingReddit'].getNextPrevLinks(this.siteTable);
```
Comment (erikdesjardins) [inline lib/modules/neverEndingReddit.js]: Removing `this.siteTable` from this call won't work because search pages have multiple "next" arrows, ugh.
