### PR TITLE
Youtube regex fix

### LINKED ISSUE #2379: Youtube (non-link) expandos are easily fakable
Due to the use of regexes in the handling of youtube expandos, it's easy to create youtube links that, when viewed using an expando show one thing, but when clicked on directly show another. I made a test post outlining how this works: https://www.reddit.com/r/puckipedia_tests/comments/3erl0x/res_youtube_breakage/

(note: this does not work on link expandos, because those use the oembed metadata in the pages)

### PR DESCRIPTION
**Pull request by erikdesjardins**
Fixes #2379

### CODE REVIEW

File: lib/modules/hosts/youtube.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ modules['showImages'].siteModules['youtube'] = {
 	handleLink: function(elem) {
 		var def = $.Deferred();
 
-		var hashRe = /^https?:\/\/(?:www\.|m\.)?youtube\.com\/watch\?.*v=([\w\-]+)/i;
+		var hashRe = /^https?:\/\/(?:www\.|m\.)?youtube\.com\/watch.*?[?&]v=([\w\-]+)/i;
```
Comment (mc10) [inline lib/modules/hosts/youtube.js]: Think we can narrow down the highlighted part a bit more, maybe with `\/watch\?(?:[^?&]+&)*?v=([\w\-]+)`. I don't know how valuable that would be though.

**Comment by mc10** [comment]
Huh after playing around with it my regex seems a bit brittle if the URL isn't perfect, like `https://www.youtube.com/watch?&av=b1WWpKEPdT4&v=dQw4w9WgXcQ` would fail to work properly.
