### PR TITLE
showImages: Support embedding all v.redd.it videos 

### LINKED ISSUE #4745: v.redd.it expansion doesn't work in /r/Dashboard
- My browser (copy from https://www.whatismybrowser.com): Chrome 65 on Windows 10
- My RES version: 5.10.3 / 5.11.8
- Am I in reddit beta (yes/no):  no

*What's the problem?*

Expanding a v.redd.it video shows blank space

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*

https://www.reddit.com/r/RESissues/comments/7zqahk/vreddit_video_expandos_dont_work_on_dashboard/
https://www.reddit.com/r/Enhancement/comments/7w7gsb/inline_vreddit_doesnt_work_in_dashboard_view/

and I have personally been experiencing it for a long time 😢 

*What other browser extensions are installed?*
Irrelevant

____

The way the expand works - When you get the page's HTML from Reddit, each post has an attribute named "data-cachedhtml" which holds the post's expansion content [as HTML], which is either a post's text, or an inline image (or gif), and it works fine, because it's just some plain HTML.
However, when sending the v.redd.it 's content, it has the HTML content including a <script> tag:

         <div class=&quot;media-preview no-constraints-when-pinned&quot; id=&quot;media-preview-8crx53&quot; style=&quot;max-width:
    486.0px; min-width: 486px; max-height: 486px; min-height: 273px; overflow: hidden;&quot;>
        <div class=&quot;media-preview-content video-player&quot;>
            <div class=&quot;no-constraints-when-pinned&quot; style=&quot;max-width: 486.0px; min-width: 486px; max-height: 486px;
                min-height: 273px&quot;>
                <div id=&quot;video-8crx53&quot; class=&quot;portrait&quot; data-hls-url=&quot;https://v.redd.it/ptrhfitarcs01/HLSPlaylist.m3u8&quot;
                    data-id-36=&quot;8crx53&quot; data-link-url=&quot;/r/aww/comments/8crx53/i_just_had_to_post_this_immediately_its_so_heckin/&quot;
                    data-mpd-url=&quot;https://v.redd.it/ptrhfitarcs01/DASHPlaylist.mpd&quot; data-obfuscated-poster-url=&quot;&quot;
                    data-orientation=&quot;portrait&quot; data-seek-preview-url=&quot;https://v.redd.it/ptrhfitarcs01/DASH_600_K&quot;
                    data-video-height=&quot;486&quot; data-video-width=&quot;486.0&quot; data-pinned-height=&quot;135&quot; data-pinned-width=&quot;135.0&quot;
                    data-max-pinned-width=&quot;240&quot; data-is-gif=&quot;false&quot;></div>
                <script type=&quot;text/javascript&quot;> (function() { var thing = {&quot;obfuscatedPosterUrl&quot;: null, &quot;context&quot;: &quot;listing&quot;, &quot;isGif&quot;: false}; var autoplay = true; if (thing.obfuscatedPosterUrl){ autoplay = false; } if (r.config && r.config.pref_no_video_autoplay && thing.context === &quot;comments&quot;) { autoplay = false; } var play_pause_click_action = autoplay ? &quot;pause&quot; : &quot;play&quot;; var play_pause_click_toggle_action = autoplay ? &quot;play&quot; : &quot;pause&quot;; var play_pause_vector_from = autoplay ? &quot;m5,5l15,7.5l0,15l-15,7.5l0,-30m15,7.5l15,7.5l0,0l-15,7.5l0,-15&quot; : &quot;m5,5l12,0l0,30l-12,0l0,-30m18,0l12,0l0,30l-12,0l0,-30&quot;; var play_pause_vector_to = autoplay ? &quot;m5,5l12,0l0,30l-12,0l0,-30m18,0l12,0l0,30l-12,0l0,-30&quot; : &quot;m5,5l15,7.5l0,15l-15,7.5l0,-30m15,7.5l15,7.5l0,0l-15,7.5l0,-15&quot;; var videoPlayerElement = $(&quot;#video-8crx53&quot;); var isMobile = r.utils.isMobile(); var canPlayDash = (typeof (window.MediaSource || window.WebKitMediaSource) === &quot;function&quot;); var videoOptions = { id: videoPlayerElement.data(&quot;id36&quot;), linkUrl: videoPlayerElement.data(&quot;linkUrl&quot;), src: canPlayDash ? videoPlayerElement.data(&quot;mpdUrl&quot;) : videoPlayerElement.data(&quot;hlsUrl&quot;), type: canPlayDash ? RedditVideoPlayer.Types.MPD : RedditVideoPlayer.Types.HLS, autoplay: autoplay, poster: null, loop: false, orientation: videoPlayerElement.data(&quot;orientation&quot;), }; if (isMobile) { videoOptions.enableStorage = false; videoOptions.uiControls = false; if (thing.isGif) { videoOptions.clickAction = RedditVideoPlayer.ClickActions.NONE; } else { videoOptions.controls = true; } } var redditVideoPlayer = new RedditVideoPlayer(videoPlayerElement, videoOptions); videoPlayerElement.data(&quot;video-player-object&quot;, redditVideoPlayer); redditVideoPlayer.setAspectRatio(videoPlayerElement.data(&quot;videoHeight&quot;) / videoPlayerElement.data(&quot;videoWidth&quot;)); if (!isMobile) { var bufferingControlsTree = $.parseHTML( '<div class=&quot;buffering-controls&quot;>' + '<div class=&quot;centered horizontal&quot;>' + '<div class=&quot;buffering-indicator active&quot;>' + '<div class=&quot;spinner-layer&quot;>' + '<div class=&quot;circle-clipper left&quot;>' + '<div class=&quot;circle&quot;></div>' + '</div>' + '<div class=&quot;gap-patch&quot;>' + '<div class=&quot;circle&quot;></div>' + '</div>' + '<div class=&quot;circle-clipper right&quot;>' + '<div class=&quot;circle&quot;></div>' + '</div>' + '</div>' + '</div>' + '</div>' + '</div>' ); var bufferingControlsOptions = { behavior: RedditVideoController.Behaviors.BUFFERING, startVisible: false, fadeInDuration: 0, fadeOutDuration: 0, }; var bufferingControls = new RedditVideoController(bufferingControlsTree, bufferingControlsOptions); redditVideoPlayer.addUiController(bufferingControls); var endedControlsTree = $.parseHTML( '<div class=&quot;ended-controls hide-when-pinned&quot;>' + '<div class=&quot;centered vertical&quot;>' + '<button data-control-type=&quot;click&quot; data-action=&quot;replay&quot;>' + '' + '</button>' + '<span class=&quot;replay-video&quot;>Replay Video</span>' + '</div>' + '</div>' ); var endedControlsOptions = { behavior: RedditVideoController.Behaviors.COMPLETED, startVisible: false, fadeInDuration: 400, fadeOutDuration: 0, }; var endedControls = new RedditVideoController(endedControlsTree, endedControlsOptions); redditVideoPlayer.addUiController(endedControls); var playbackControlsTree = $.parseHTML( '<div class=&quot;playback-controls right bottom left hide-when-pinned&quot;>' + '<a class=&quot;control-button permalink&quot; ' + 'tooltip-string=&quot;View post on Reddit&quot;' + 'data-control-type=&quot;click&quot; ' + 'href=&quot;/r/aww/comments/8crx53/i_just_had_to_post_this_immediately_its_so_heckin/&quot;>' + '' + '</a>' + '<button ' + 'class=&quot;control-button play-pause&quot; ' + 'tooltip-string=&quot;Pause&quot;' + 'tooltip-string-toggle=&quot;Play&quot; ' + 'data-control-type=&quot;click&quot; ' + 'data-action=&quot;' + play_pause_click_action + '&quot; ' + 'data-toggle-action=&quot;' + play_pause_click_toggle_action + '&quot;>' + '<svg class=&quot;play-pause&quot; viewbox=&quot;0 0 40 40&quot;>' + '<path d=&quot;' + play_pause_vector_to + '&quot;>' + '<animate ' + 'begin=&quot;indefinite&quot; ' + 'attributeType=&quot;XML&quot; ' + 'attributeName=&quot;d&quot; ' + 'fill=&quot;freeze&quot; ' + 'to=&quot;' + play_pause_vector_to + '&quot; ' + 'from=&quot;' + play_pause_vector_from + '&quot; ' + 'dur=&quot;0.1s&quot; ' + 'keySplines=&quot;.4 0 1 1&quot; ' + 'repeat=&quot;1&quot;>' + '</animate>' + '</path>' + '</svg>' + '</button>' + '<span class=&quot;time-label&quot; ' + 'data-control-type=&quot;text&quot; ' + 'data-action=&quot;elapsedTime&quot;>' + '0:00' + '</span>' + '<div data-control-type=&quot;seekBar&quot; ' + 'data-preview-video-src=&quot;' + videoPlayerElement.data('seekPreviewUrl') + '&quot;>' + '</div>' + '<span class=&quot;time-label&quot; ' + 'data-control-type=&quot;text&quot; ' + 'data-action=&quot;totalTime&quot;>' + '0:00' + '</span>' + '<div class=&quot;control-button volume-container&quot;>' + '<div data-control-type=&quot;volumeSlider&quot;></div>' + '<button class=&quot;volume&quot; data-control-type=&quot;click&quot; data-action=&quot;unmute&quot; data-toggle-action=&quot;mute&quot;>' + '' + '' + '</button>' + '</div>' + '<div class=&quot;control-button settings-container&quot; ' + 'tooltip-string=&quot;Settings&quot;>' + '<label class=&quot;settings has-submenu&quot; data-control-type=&quot;click&quot;>' + '<input class=&quot;settings&quot; type=&quot;checkbox&quot;>' + '' + '' + '<span class=&quot;submenu&quot;>' + '<div data-control-type=&quot;settingsMenu&quot;></div>' + '</span>' + '</label>' + '</div>' + '<button class=&quot;control-button fullscreen&quot; ' + 'tooltip-string=&quot;Fullscreen&quot;' + 'tooltip-string-toggle=&quot;Exit Fullscreen&quot; ' + 'data-control-type=&quot;click&quot; ' + 'data-action=&quot;fullscreenRequest&quot; ' + 'data-toggle-action=&quot;fullscreenCancel&quot;>' + '' + '' + '</button>' + '</div>' ); var playbackControlsOptions = { behavior: RedditVideoController.Behaviors.MOUSE_MOVE, }; var playbackControls = new RedditVideoController(playbackControlsTree, playbackControlsOptions); redditVideoPlayer.addUiController(playbackControls); if (r.config && r.config.pref_no_video_autoplay && thing.context === &quot;comments&quot;) { var interstitialControlsTree = $.parseHTML( '<div class=&quot;interstitial-controls hide-when-pinned&quot;>' + '<div class=&quot;centered vertical&quot;>' + '<button data-control-type=&quot;click&quot; data-action=&quot;play&quot;>' + '<svg class=&quot;play-pause&quot; viewbox=&quot;0 0 36 36&quot;>' + '<path d=&quot;m5,5l15,7.5l0,15l-15,7.5l0,-30m15,7.5l15,7.5l0,0l-15,7.5l0,-15&quot;></path>' + '</svg>' + '</button>' + '</div>' + '</div>' ); var interstitialControlsOptions = { behavior: RedditVideoController.Behaviors.INTERSTITIAL, startVisible: true, fadeInDuration: 0, fadeOutDuration: 400, }; var interstitialControls = new RedditVideoController(interstitialControlsTree, interstitialControlsOptions); redditVideoPlayer.addUiController(interstitialControls); } $(playbackControlsTree).find('input.settings').change(function() { if ($(this).is(':checked')) { firePlayerEvent.call(redditVideoPlayer, null, null, {verb: 'click', noun: 'settings'}); redditVideoPlayer.setClickAction(RedditVideoPlayer.ClickActions.NONE); } else { redditVideoPlayer.setClickAction(RedditVideoPlayer.ClickActions.PLAY_PAUSE); } }); } if (isMobile && thing.isGif) { $(videoPlayerElement).find(&quot;video&quot;).bind(&quot;webkitendfullscreen&quot;, function() { this.play(); }); redditVideoPlayer.mute(); } $(document.body).on(&quot;interstitial:destroy&quot;, function(event) { if (&quot;t3_8crx53&quot; == event.expando.id) { redditVideoPlayer.play(); } }); var parent = $(&quot;#media-preview-8crx53&quot;).parent(); var hadInterstitial = parent.hasClass(&quot;expando&quot;) && !(parent.hasClass(&quot;expando--with-interstitial&quot;)) && !(parent.hasClass(&quot;expando-uninitialized&quot;)) && &quot;&quot; != &quot;&quot;; if (hadInterstitial && !isMobile) { $(videoPlayerElement).find(&quot;video&quot;)[0].addEventListener(&quot;canplay&quot;, function() { redditVideoPlayer.play(); }) } var playPauseButtons = $(videoPlayerElement).find(&quot;button.play-pause&quot;); var isPlaying = autoplay; redditVideoPlayer.addActionCompletedCallback(function(action, value) { if ((action == RedditVideoPlayer.Actions.PLAY && !isPlaying) || (action == RedditVideoPlayer.Actions.PAUSE && isPlaying)) { playPauseButtons.each(function() { var animation = $(this).find('animate').first(); var to = animation.attr('to'); var from = animation.attr('from'); animation.attr({ &quot;from&quot;: to, &quot;to&quot;: from }); if ('beginElement' in animation[0]) { animation.get(0) .beginElement(); } else { var path = $(this).find('path'); path.attr({&quot;d&quot;: from}); } }); isPlaying = !isPlaying; } else if (action == RedditVideoPlayer.Actions.NONE && thing.isGif && isMobile) { redditVideoPlayer.toggleFullScreen(); return; } var settings = $(playbackControlsTree).find(&quot;input.settings&quot;); if (settings.prop(&quot;checked&quot;)) { settings.prop(&quot;checked&quot;, false); redditVideoPlayer.setClickAction(RedditVideoPlayer.ClickActions.PLAY_PAUSE); } }); function firePlayerEvent(action, value, extras) { extras = (typeof extras === 'object') ? extras : {}; var verb = extras.verb || ''; var noun = extras.noun || ''; var source = extras.source || 'videoplayer'; var maxTimestamp = this.maxPlayed * 1000; var durationMs = this.duration * 1000; var timeMs = this.currentTime * 1000; var pinnableElement = $(this.root).closest('.pinnable-content'); var targetElement = $(this.root).closest('.thing.link'); var targetData = targetElement.data(); var videoState = { maxTimestampServed: parseInt(maxTimestamp), percentServed: maxTimestamp / durationMs, duration: parseInt(durationMs), time: parseInt(timeMs), isNsfw: targetElement.hasClass('over18'), isSpoiler: targetElement.hasClass('spoiler'), isPinned: pinnableElement.hasClass('pinned'), isVertical: this.orientation === RedditVideoPlayer.Orientations.PORTRAIT, firstFrameTime: this.firstFrameTime, loadStartTime: this.loadStartTime, }; r.analytics.videoPlayerEvent(source, verb, noun, targetData, videoState); } redditVideoPlayer.addActionCompletedCallback(firePlayerEvent); $(playbackControlsTree).find('a.permalink').click(function() { firePlayerEvent.call(redditVideoPlayer, null, null, {verb: 'click', noun: 'snoo'}); }); })(); </script> </div>
        </div>
    </div>

On RES' dashboard.js (Reddit-Enhancement-Suite/lib/modules/dashboard.js), when populating the widget's content (this.populate [currently line 740 ¯\_(ツ)_/¯]), all the <script> tags are removed (for security reasons I assume).
````
    $widgetContent.html($widgetContent.html().replace(/<script(.|\s)*?\/script>/g, ''));
````
I tried to comment this line out, and it fixes the v.redd.it links, which confirmed my theory, but this may not be production-approved, since it can be a security risk.

### PR DESCRIPTION
**Pull request by larsjohnsen**
Allows inlining v.redd.it links, and to replace the native player for faster and improved user experience.

- Uses the dash.js library
  - Since it is fairly large, it's loaded separate from the foreground bundle and only on demand
- When `forceReplaceNativeExpando` is enabled, Reddit's video player script is no longer loaded
  - Improves load times a little

Relevant issue: Fixes #4745
Tested in browser: Firefox 79, Chrome 85

### CODE REVIEW

File: lib/modules/hosts/vreddit.js [hunk 1]
```diff
@@ -1,42 +1,33 @@
...
+	permissions: ['https://v.redd.it/*/HLSPlaylist.m3u8'],
 	attribution: false,
 	options: {
-		replaceNativeExpando: {
-			title: 'showImagesReplaceNativeExpandoTitle',
-			description: 'showImagesReplaceNativeExpandoDesc',
-			value: false,
+		forceReplaceNativeExpando: {
+			title: 'showImagesVredditForceReplaceNativeExpandoTitle',
+			description: 'showImagesVredditForceReplaceNativeExpandoDesc',
```
Comment (BenMcGarry) [inline lib/modules/hosts/vreddit.js:13]: i18n keys need creating in en.json

**Comment by larsjohnsen** [comment]
Updated to use dash.js instead of hls.js as higher bitrates are available in the the `.mpd` file.

**Comment by canDry** [comment]
:+1:  Kudos to all involved... it's working!!
