### PR TITLE
If element is not inside a thing, fallback to first visible thing

### LINKED ISSUE #3426: Thing-based macro placeholders eg subreddit broken in reply to post
https://www.reddit.com/r/RESissues/comments/520jsx/bug_macros_with_placeholder_stuff_dont_work/

For adding a top-level comment, Thing(textarea) isn't finding the post.

### PR DESCRIPTION
**Pull request by andytuba**
Fixes #3426: if the reference element (e.g. "add a comment" text area on top-level comment) isn't inside a thing, use the first visible thing and assume it's the main thing, e.g. on a comments page, the original post.  May need refining later.

also some incidental fixups

### CODE REVIEW

**Comment by andytuba** [comment]
wait, this did not work

**Comment by andytuba** [comment]
wait, this does work, but testing in inbox uncovered a related issue.

File: lib/utils/Thing.js [hunk 1]
```diff
@@ -129,7 +134,7 @@ export default class Thing {
 	}
 
 	isComment() {
-		return this.thing.classList.contains('comment');
+		return this.thing.classList.contains('comment') || this.thing.classList.contains('was-comment');
```
Comment (andytuba) [inline lib/utils/Thing.js]: `was-comment` is a comment in your inbox

File: lib/utils/Thing.js [hunk 2]
```diff
@@ -32,12 +32,17 @@ export default class Thing {
 		return Thing.visibleThingElements().map(ele => new Thing(ele));
 	}
 
+	static elementFor(element) {
+		return $(element).closest(Thing.thingSelector).get(0) || Thing.visibleThingElements()[0];
```
Comment (erikdesjardins) [inline lib/utils/Thing.js]: Acknowledging that this is kinda hacky, but I don't think it'll cause any problems since almost everything we interact with is within a `.thing` already

File: lib/utils/Thing.js (hunk 1 above)
Comment (erikdesjardins) [inline lib/utils/Thing.js]: Looks like comments in your inbox previously would return false for both `isComment` and `isLink`, so this shouldn't break anything.

In the future maybe we should use the attr `data-type = link|comment|message`

**Comment by erikdesjardins** [comment]
```
/home/travis/build/honestbleeps/Reddit-Enhancement-Suite/lib/modules/commentTools.js
  719:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  722:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
```

Otherwise LGTM

File: lib/utils/Thing.js (hunk 2 above)
Comment (andytuba) [inline lib/utils/Thing.js]: Deffo hacky. Hopefully this won't generate too many more bugs.

File: lib/utils/Thing.js (hunk 1 above)
Comment (andytuba) [inline lib/utils/Thing.js]: and potentially `|comment-message` too, since PMs and comment replies have different markup in the inbox.
